#!/usr/bin/env python3

from requests import get
from pyhunter import PyHunter
from argparse import ArgumentParser
from re import findall
from pathlib import Path
import json

# TODO: write fetching other domains logic 
# TODO: 
def skymem(domain:str,fetch_subdomains:bool) -> list:
    """Fetch emails from Skymem.
    Takes 2 arguments:
        - domain to be searched
        - a bool value tells whether to fetch other domains or not"""
    
    # you should search for your target then you get a link for the mail addreses
    url = findall(r"/domain/[^\"]+",get(f"https://www.skymem.info/srch?q={domain}").text)
    
    # the mails are displayed in two pages so i try once with 2 (Exist by default in the url), then with 1
    emails = findall(rf"[^>=?:]+@{domain}",get("https://www.skymem.info"+url[0]).text)
    emails.extend(findall(rf"[^>=?:]+@{domain}",get("https://www.skymem.info"+url[0].split("=")[0]+"=1").text))
    return emails

def pwned(email:str) -> bool:
    response = get(f"https://api.haveibeenpwned.com/unifiedsearch/{email}")
    # if response.status_code ==200:
    print(response.content)

def hunter(domain:str,key:str) -> list:
    hunter_api = PyHunter(key)
    hunter_api.domain_search(domain)

if __name__ == "__main__":
    parser = ArgumentParser(description="Get Emails")
    parser.add_argument('-d','--domain',help='Domain name')
    # parser.add_argument('--skymem',action="store_true",help="retrieve from Skymem")
    parser.add_argument('--subdomains',action="store_true",help="Fetch any subdomains if available")
    # parser.add_argument('--pwned',action="store_true",help="Check if the email is pwned by haveibeenpwned.com")
    parser.add_argument('-s','--source',help="Specify the sources: Skymem, Hunter,")

    args = parser.parse_args()
    emails = []
    keys = json.loads(open(f"{Path.home()}/.config/enumail/keys.json","r").read())

    sources = args.source.lower()
    if "skymem" in sources:
        emails.extend(skymem(args.domain,args.subdomains))
    
    if "hunter" in sources:
        hunter(args.domain,keys['hunter'])
    # if args.pwned:
    #     for email in emails:
    #         pwned(email)
    # for email in set(emails):
    #     print(email)